name: Build

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1]
    
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.java-version }}
          php_extensions: ext-bcmath xdebug
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.java-version }}
          php_extensions: ext-bcmath xdebug
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit .
    